// <auto-generated />
namespace TheAmazingBookStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FluentAPIManytoMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluentAPIManytoMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201710200944108_Fluent-API-Many-to-Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
